name: CI/CD for Node.js REST-API

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker Image
        run: docker build -t bishal5438/rest-api .

      - name: Push to DockerHub
        run: docker push bishal5438/rest-api:latest 

  Deploy:
    runs-on: self-hosted

    steps:
      - name: Pull the Docker Image
      #It isn't wise to use docker with sudo, Instead we should add current user to docker group. 
        run: sudo docker pull bishal5438/rest-api:latest 

      - name: Delete Old Container
        run: |
          if [ "$(docker ps -q -f name=rest-api-Container)" ]; then
            sudo docker rm -f rest-api-Container
          fi

      - name: Run the Container
        run: sudo docker run -d -p 80:80 --name rest-api-Container bishal5438/rest-api
